services:
  atividade_service:
    build:
      context: ./atividade_service
    container_name: atividade_service
    ports:
      - '5002:5002'
    volumes:
      - ./atividade_service:/app
      - ./atividade_service/db_data:/app/app_data # Pasta local -> pasta no container
    networks:
      - api-network

  pessoa_service:
    build:
      context: ./pessoa_service
    container_name: pessoa_service
    ports:
      - '5001:5001'
    volumes:
      - ./pessoa_service:/app
      - ./pessoa_service/db_data:/app/app_data
    networks:
      - api-network

networks:
  api-network:
    external: true
